name: MVC App Actions
      
on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  
  run-tests:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        matlab-version: [R2026a]
    runs-on: ${{ matrix.platform }}    
    continue-on-error: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Start a display server for jobs running on Linux
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV      

      - name: Set up MATLAB on the runner
        uses: matlab-actions/setup-matlab@v2
        with:
          products: MATLAB      
          release: ${{ matrix.matlab-version }}

      - name: Run the toolbox tests
        uses: matlab-actions/run-command@v2
        with:
            command: |
                toolboxFile = websave( "TestFrameworkExtensions.mltbx", "https://github.com/mathworks/test-framework-extensions/releases/latest/download/TestFrameworkExtensions.mltbx" );
                fileCleanup = onCleanup( @() delete( toolboxFile ) );
                matlab.addons.install( toolboxFile, true );
                openProject( "MVC.prj" );
                buildtool test

  package-and-release-toolbox:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4   

    - name: Extract version from tag
      shell: bash
      run: |
        VERSION="${GITHUB_REF_NAME#v}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Extract release notes
      id: changelog
      shell: bash
      run: |
        RELEASEBODY=$(awk -v ver="$VERSION" '
            /^## Version / {
                if (p) { exit }          # stop at next version block
                if ($3 == ver) {         # match "Version X.Y.Z"
                    p=1
                    next
                }
              }
              p && NF
            ' tbx/mvcapp/Changelog.md)

         {
            echo "RELEASEBODY<<EOF"
            echo "$RELEASEBODY"
            echo "EOF"
         } >> $GITHUB_OUTPUT

    # - name: Extract release notes
    #   shell: bash
    #   id: extract_notes
    #   run: |
    #     TAG_NAME="${{ github.event.release.tag_name }}"
    #     awk "/^## Version $TAG_NAME\$/ {flag=1; next} /^## Version / {flag=0} flag" tbx/mvcapp/Changelog.md > RELEASE_NOTES.md
    #     sed -i ':a;/^\n*$/{$d;N;ba}' RELEASE_NOTES.md        
    #     echo "notes<<EOF" >> $GITHUB_OUTPUT
    #     cat RELEASE_NOTES.md >> $GITHUB_OUTPUT
    #     echo "EOF" >> $GITHUB_OUTPUT

    - name: Set up MATLAB on the runner
      uses: matlab-actions/setup-matlab@v2
      with:
        products: MATLAB    

    - name: Package toolbox
      uses: matlab-actions/run-build@v2
      with:
        tasks: package
        build-options: -skip test -skip check

    - name: Release toolbox
      uses: softprops/action-gh-release@v2
      with:
        name: MVC App ${{ env.VERSION }}
        tag_name: v${{ env.VERSION }}
        body: ${{ steps.changelog.outputs.RELEASEBODY }}
        draft: false
        make_latest: true
        files: releases/MVC_App.mltbx
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}